
= Session 2
#let img_path = "../img/session-2/"

In this session, we built and tested the analog conditioning circuit for a MEMS microphone. The circuit was implemented with the INA131 instrumentation amplifier and checked using the oscilloscope.

The main goal was to verify that the microphone signal could be detected and amplified correctly before using it with the DAQ in the next session.

== Power supply check

Before testing the circuit, we checked the supply voltages with a multimeter. The INA131 was supplied with approximately $+12$ V and $-12$ V. The MEMS microphone was supplied with approximately 2 V, which is the typical value indicated in its datasheet.

#figure(
  grid(
    columns: (1fr, 1fr),
    gutter: 1em,
    image(img_path + "+12V.jpeg", width: 80%),
    image(img_path + "-12V.jpeg", width: 80%),
  ),
  caption: [Positive and negative supply voltages for the INA131]
)

#figure(
  image(img_path + "2V.jpeg", width: 40%),
  caption: [Microphone supply voltage]
)

== Circuit implementation

The analog microphone and the INA131 amplifier were connected on the protoboard. The circuit was used to amplify the small signal generated by the microphone and observe it more clearly on the oscilloscope.

#figure(
  image(img_path + "circuito.jpeg", width: 60%),
  caption: [Analog conditioning circuit implemented on the protoboard]
)

== Microphone test

To test the circuit, we generated acoustic tones with a smartphone application and placed the phone close to the microphone. Then, the output signal was observed with the oscilloscope. This allowed us to check if the circuit is working correctly.

#figure(
  image(img_path + "micro analogico mer e ines.jpeg", width: 60%),
  caption: [Acoustic tone test with the analog MEMS microphone]
)

Some tones were tested, as shown in the following figures. For each case, we observed the signal in the time domain and also its FFT, where the main tone frequency can be identified more clearly.

#figure(
  grid(
    columns: (1fr, 1fr),
    gutter: 1em,
    image(img_path + "parte1foto1agusyjavi.jpeg", width: 80%),
    image(img_path + "parte1foto2agusyjavi.jpeg", width: 80%),
  ),
  caption: [Time-domain signal and FFT for the first acoustic tone]
)

#figure(
  grid(
    columns: (1fr, 1fr),
    gutter: 1em,
    image(img_path + "parte2foto1agusyjavi.jpeg", width: 80%),
    image(img_path + "parte2foto2agusyjavi.jpeg", width: 80%),
  ),
  caption: [Time-domain signal and FFT for the second acoustic tone]
)

== Complete circuit test

Finally, we tested the complete circuit. The oscilloscope showed a clear signal, so the microphone and the amplification stage were working properly. In this measurement, the signal had an amplitude of about 4 V peak-to-peak and a frequency close to 1.44 kHz.

#figure(
  image(img_path + "primer micro mer e ines CON TODO EL CIRCUITO.jpeg", width: 60%),
  caption: [Output signal measured with the complete conditioning circuit]
)

In this session, we verified with the measurements shown in the oscilloscope that the MEMS microphone detected the sound and that the INA131 amplified the signal correctly.