= Power supply and electrical integration
== Design objective

The instrumentation system must be powered either from the aircraft DC bus, nominally 28 V, or from an auxiliary 24 V battery. The power architecture must therefore tolerate a noisy high-voltage input and generate low-noise supply rails for the analog front-end, the AD7606C-18 acquisition ICs, the MEMS-adjacent LNAs, and the FPGA-based digital acquisition stage.

The proposed architecture uses a cascaded supply tree. A first switching converter reduces the 24 V / 28 V input to an intermediate 7 V rail. From this rail, separated analog and digital branches are generated. Sensitive analog rails are produced using low-noise linear regulators, while the high-current FPGA core rails are generated with dedicated switching regulators.

== Power tree

#figure(
  align(center)[
    #box(inset: 8pt, stroke: 0.7pt, radius: 4pt)[
      #grid(
        columns: (1fr,),
        row-gutter: 8pt,
        align: center,

        [#strong[24 V battery / 28 V aircraft bus]],
        [$arrow.b$],
        [#strong[Input protection + EMI filter]],
        [$arrow.b$],
        [#strong[Main buck converter: 24/28 V $arrow.r$ 7 V]],
        [$arrow.b$],
        [
          #grid(
            columns: (1fr, 1fr),
            column-gutter: 24pt,
            align: center,

            [
              #box(inset: 6pt, stroke: 0.7pt, radius: 4pt)[
                #strong[Analog branch] \
                7 V $arrow.r$ low-noise LDO $arrow.r$ $5 V_A$ \
                #smallcaps[AD7606C-18] AVCC \
                MEMS LNA / buffer \
                ADC reference and bias
              ]
            ],
            [
              #box(inset: 6pt, stroke: 0.7pt, radius: 4pt)[
                #strong[Digital branch] \
                7 V $arrow.r$ $5 V_D$ \
                5 $V_D$ $arrow.r$ 3.3 $V_D$ \
                5 $V_D$ $arrow.r$ 1.8 V / 1.0 V FPGA rails
              ]
            ],
          )
        ],
      )
    ]
  ],
  caption: [Proposed cascaded power architecture.]
)

== Input stage

The input stage protects the system from abnormal operating conditions and reduces conducted noise before the first DC/DC conversion.

Main elements:

- Fuse or resettable fuse for overcurrent protection.
- TVS diode for transient suppression.
- Reverse polarity protection, preferably using an ideal-diode MOSFET stage.
- Common-mode and differential EMI filtering.
- Bulk capacitance after the protection stage to absorb input disturbances.

The switching converter connected to this input generates an intermediate voltage of approximately 7 V. This value gives enough dropout margin for 5 V low-noise LDOs while reducing their power dissipation compared with regulating directly from 24 V or 28 V.

== Analog supply branch

The analog branch supplies the sensitive parts of the system:

- The analog supply of the AD7606C-18 devices.
- The LNA or high-impedance buffer placed close to each MEMS output.
- The ADC reference and analog bias circuitry.

The proposed rail is:

```text
7 V → low-noise LDO → 5 V_A
```

The 5 V_A rail must be kept separate from the digital 5 V rail. Even if both rails have the same nominal voltage, the analog branch must not share high-current digital return paths with the FPGA or communication interface.

Each zone should include local filtering:

```text
5 V_A global → ferrite / RC filter → local 5 V_A_zone
```

Local decoupling must be placed close to every AD7606C-18 and every LNA. The LNA supply is especially critical because it is physically close to the MEMS transducer and directly affects the input-referred noise of the acquisition chain.

== Digital supply branch

The digital branch supplies the digital interface of the ADCs, the FPGA I/O banks, and the auxiliary logic.

The proposed cascade is:

```text
7 V → 5 V_D → 3.3 V_D
```

The 3.3 $V_D$ rail supplies:

- AD7606C-18 VDRIVE.
- FPGA I/O banks connected to the ADCs.
- Low-speed control logic.

The FPGA core rails should not be generated using linear regulators from 7 V or 5 V due to excessive power dissipation. Instead, dedicated switching regulators should be used:

```text
5 V_D → buck → 1.0 V FPGA core
5 V_D → buck or LDO → 1.8 V FPGA auxiliary rail
```

== Rail summary

#table(
columns: (1.2fr, 2.2fr, 2.5fr),
inset: 6pt,
align: left,
table.header([Rail], [Main loads], [Design notes]),

[7 V],
[Intermediate bus],
[Generated by the main buck converter from 24/28 V. Not used directly for sensitive circuitry.],

[5 V_A],
[AD7606C-18 AVCC, MEMS LNAs, analog bias],
[Low-noise LDO. Local filtering per zone. Separated from digital return currents.],

[5 $V_D$],
[Digital pre-regulation rail],
[Feeds 3.3 $V_D$ and FPGA regulators. Can be generated with a switching regulator.],

[3.3 $V_D$],
[AD7606C-18 VDRIVE, FPGA I/O],
[Must match the selected FPGA I/O voltage.],

[1.8 V],
[FPGA auxiliary supply, optional logic],
[Generated according to FPGA requirements.],

[1.0 V],
[FPGA core],
[Dedicated high-efficiency buck regulator.]
)

== Distribution to the acquisition zones

The system is divided into ten identical acquisition zones. Each zone contains two AD7606C-18 devices: one for the LF outputs and one for the HF outputs. Therefore, the power distribution must be replicated carefully across the ten zones.

Per zone:

```text
5 V_A_zone → 2 x AD7606C-18 AVCC + local LNA/buffer stages
3.3 $V_D$ zone → 2 x AD7606C-18 VDRIVE + digital interface
GND_A / GND_D → controlled return connection
```

The analog supply should be filtered locally in each zone to prevent noise coupling between zones. The digital supply can be distributed more globally, but it still requires local decoupling close to every ADC.

== Grounding and layout considerations

The PCB layout must prevent digital switching currents from flowing through the analog reference path. The recommended strategy is to use a solid ground plane with careful partitioning of current return paths, rather than isolated ground islands connected unpredictably.

Key layout rules:

* Place the LNA or buffer as close as possible to the MEMS output.
* Place decoupling capacitors close to every supply pin.
* Keep ADC reference routing short and shielded from digital lines.
* Separate fast FPGA/ADC digital buses from MEMS and LNA inputs.
* Route analog inputs symmetrically inside each zone.
* Avoid sharing narrow return paths between FPGA currents and analog front-end currents.

== Power sequencing and monitoring

The FPGA and ADCs require a defined power-up sequence. The power system should therefore include voltage supervision and reset generation.

Recommended signals:

```text
POWER_GOOD_5V_A
POWER_GOOD_3V3_D
POWER_GOOD_FPGA
GLOBAL_RESET
``` 

The FPGA should remain in reset until all required rails are stable. Optionally, the FPGA can monitor voltage and current sensors to detect failures in the acquisition zones.

== Preliminary design conclusion

The proposed power architecture is:


24/28 V input
→ protection and EMI filtering
→ 7 V intermediate switching rail
→ separated analog and digital cascaded branches
→ local filtering and decoupling per acquisition zone

This architecture reduces dissipation, isolates the sensitive analog front-end from digital noise, and provides suitable supply rails for the AD7606C-18 devices, the MEMS-adjacent LNAs, and the FPGA acquisition system.

