version: "3.8"

services:
  middleware:
    build:
      context: ./middleware
    network_mode: host
    environment:
      - MICRO_UDP_PORT=5001
      - MICRO_MCU_IP=192.168.88.99
      - MICRO_MCU_UDP_PORT=5000
      - MICRO_HTTP_PORT=8080
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:latest
    network_mode: host
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana:latest
    network_mode: host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3001
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=10ms
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
